# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mktodo < Formula
  desc ""
  homepage "https://github.com/KolbyMcGarrah/mktodo"
  version "0.1.5"

  on_macos do
    url "https://github.com/KolbyMcGarrah/mktodo/releases/download/v0.1.5/mktodo_0.1.5_darwin_all.tar.gz"
    sha256 "bf10e537e2d8100b484a3f3e5951b8349b358ee48c925659d5cd3b1892d10136"

    def install
      bin.install "mktodo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KolbyMcGarrah/mktodo/releases/download/v0.1.5/mktodo_0.1.5_linux_arm64.tar.gz"
      sha256 "1079ef3778ebac6fdfb9c51cf0d3d00caaf4335fa759bf8fce12897003d36d3e"

      def install
        bin.install "mktodo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KolbyMcGarrah/mktodo/releases/download/v0.1.5/mktodo_0.1.5_linux_amd64.tar.gz"
      sha256 "dbddc8cfbef332000a5260e921a5800c252f56e9664833b4cfac187989e69947"

      def install
        bin.install "mktodo"
      end
    end
  end
end
