# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc ""
  homepage "https://github.com/KolbyMcGarrah/cli-todo"
  version "0.0.1"

  on_macos do
    url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.1/cli-todo_0.0.1_darwin_all.tar.gz"
    sha256 "08e3ac151d4d93d4a1295f9a447d7f5fca5cf6941d4a072123d8df27fa47f890"

    def install
      bin.install "cli-todo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.1/cli-todo_0.0.1_linux_arm64.tar.gz"
      sha256 "18bb687bf872917323f7d3960fff9dc9444656e0863c3139560a628a98d0e278"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.1/cli-todo_0.0.1_linux_amd64.tar.gz"
      sha256 "09f791b2ef6d3ace5f74db8232411bad778a8a180970fdeaf96dfa4bbaafefc8"

      def install
        bin.install "todo"
      end
    end
  end
end
