# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc ""
  homepage "https://github.com/KolbyMcGarrah/cli-todo"
  version "0.0.2"

  on_macos do
    url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.2/cli-todo_0.0.2_darwin_all.tar.gz"
    sha256 "904c8319dc01ec68d185ff65a241e6bf75c784ef0a12d972185936dd28e43806"

    def install
      bin.install "cli-todo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.2/cli-todo_0.0.2_linux_arm64.tar.gz"
      sha256 "6b5d491aa59431506d46d90998c6ae5fda71f5fc795500ffcd884f24c91c7c83"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.2/cli-todo_0.0.2_linux_amd64.tar.gz"
      sha256 "f8c2d87b7d1353d3a5b3e833a5576749fdba483161cfcc2236ec999e1caa1516"

      def install
        bin.install "todo"
      end
    end
  end
end
