# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Todo < Formula
  desc ""
  homepage "https://github.com/KolbyMcGarrah/cli-todo"
  version "0.0.3"

  on_macos do
    url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.3/cli-todo_0.0.3_darwin_all.tar.gz"
    sha256 "3a3baa591112193a67aa216cd7bed6f74193b2b2af6502690fb1be5d33a7e84e"

    def install
      bin.install "cli-todo"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.3/cli-todo_0.0.3_linux_arm64.tar.gz"
      sha256 "7f2d1f5568bd694c2aa5797afe147d7a119bf25e65f34eeec80c3cc5abc0b3a8"

      def install
        bin.install "todo"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/KolbyMcGarrah/cli-todo/releases/download/v0.0.3/cli-todo_0.0.3_linux_amd64.tar.gz"
      sha256 "e1416c7f6ed2aea5c15a3dba15f69e9487fc8cd61c3ceb7c9b7105b0ac97f1c4"

      def install
        bin.install "todo"
      end
    end
  end
end
